### ISSUE TITLE
Add transcode from beancount/ledger/hledger to knut

### ISSUE THREAD

**Issue by PaulsTek** [sboehler/knut#12]
Right now I can create a beancount ledger from a knut ledger file, but not the opposite - the syntax is sufficiently different that I cannot just use find and replace.  So far these are the issues I have, and there may be others, and need to make my own transcoder:
- replace ";" with "#" for comment lines
- remove "*" after date
- remove leading spaces from debit account row
- combine debit and credit account rows
- other differences??

eg:
beancount syntax:
2020-01-10 * "CITY UTILITY PAYMENT"
  Assets:WellsFargo:Chk                             -10.00  USD
  Expenses:Home:WaterAndTrash               10.00  USD

knut syntax:
2023-01-05 "CITY OF DENTON UTILITY"
Assets:WellsFargo:Chk     Expenses:Home:WaterAndTrash      -70.00  USD

**Comment by sboehler** [comment]
Great idea! The complexity is mostly on the side of parsing the formats of the other tools, I don't think I would like to maintain a parser for all these formats in knut's code base. Having a standalone converter would make a lot of sense though - if you publish yours, happy to link it in the docs.
